# Generated by Django 5.2 on 2025-04-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_drink_alter_orderitem_pizza_alter_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sauces/')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sauce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.sauce'),
        ),
    ]
